version: '3.2'
services:
  aas:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: [
        "/usr/local/bin/aas",
        "--config-file",
        "/etc/aas/config.toml",
      ]
    restart: always # keep the server running
    ports:
      - "8080:8080"
    volumes:
      - ./docker-compose/aas:/etc/aas:rw
    depends_on:
    - coco-as

  coco-as:
    image: ghcr.io/confidential-containers/staged-images/coco-as-restful:9b8ef6c4b7736835c56b38f885833107a755bd98
    ports:
    - "50004:50004"
    restart: always
    volumes:
    - ./docker-compose/coco-as/as-config.json:/etc/config.json:rw
    - ./docker-compose/coco-as/sgx_default_qcnl.conf:/etc/sgx_default_qcnl.conf:rw
    command: [
      "restful-as",
      "--socket",
      "0.0.0.0:50004",
      "--config-file",
      "/etc/config.json"
    ]
